apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app_tenant_deploy_eks-app
  namespace: bh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: eks-app
    spec:
      containers:
      - name: app_tenant_pod_eks-app
        image: eks-app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app_tenant_svc_eks-app
  labels:
    name: app_tenant_eks-app
  namespace: bh
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    name: eks-app
