apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app_tenant_deploy_CapDev_node
  namespace: kube-public
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: CapDev_node
    spec:
      containers:
      - name: app_tenant_pod_CapDev_node
        image: CapDev_node:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app_tenant_svc_CapDev_node
  labels:
    name: app_tenant_CapDev_node
  namespace: kube-public
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    name: CapDev_node
