apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app_tenant_deploy_capdev
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: capdev
    spec:
      containers:
      - name: app_tenant_pod_capdev
        image: capdev:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app_tenant_svc_capdev
  labels:
    name: app_tenant_capdev
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    name: capdev
