apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app_tenant_deploy_node
  namespace: dnfdf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: node
    spec:
      containers:
      - name: app_tenant_pod_node
        image: node:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app_tenant_svc_node
  labels:
    name: app_tenant_node
  namespace: dnfdf
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    name: node
