apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app_tenant_deploy_uservice
  namespace: tenant-uservice-a1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: uservice
    spec:
      containers:
      - name: app_tenant_pod_uservice
        image: uservice:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app_tenant_svc_uservice
  labels:
    name: app_tenant_uservice
  namespace: tenant-uservice-a1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    name: uservice
